[BAYCKRC_UR500]
extends = esp32_base
board = esp32-c3-devkitm-1
build_flags =
  ${esp32_base.build_flags}
  -I variants/bayckrc_ur500
  -D ESP32_CPU_FREQ=80
  ;-D PIN_VBAT_READ=D0
  -D PIN_BOARD_SDA=18 ; serial rx
  -D PIN_BOARD_SCL=19 ; serial tx
  -D PROMICRO_LR1121
  -D RADIO_CLASS=CustomLR1121
  -D WRAPPER_CLASS=CustomLR1121Wrapper
  -D LORA_TX_POWER=1
  -D LR11X0_DIO_AS_RF_SWITCH=true
  -D LR11X0_DIO3_TCXO_VOLTAGE=3.3
  -D RF_SWITCH_TABLE
  -D RX_BOOSTED_GAIN=1
  -D P_LORA_DIO_1=1
  -D P_LORA_DIO_9=1
  -D P_LORA_BUSY=3
  -D P_LORA_NSS=7
  -D P_LORA_RESET=2
  -D P_LORA_SCLK=6
  -D P_LORA_MISO=5
  -D P_LORA_MOSI=4
   ; "led_rgb": 8,
   ; "led_rgb_isgrb": true,
   ; "radio_dcdc": true,
   ; "button": 9
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/bayckrc_ur500>
  +<helpers/sensors>
lib_deps =
  ${esp32_base.lib_deps}

[env:BAYCKRC_UR500_repeater]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${BAYCKRC_UR500.build_flags}
  ${sensor_base.build_flags}
  -UENV_INCLUDE_GPS
  -UENV_INCLUDE_VL53L0X
  -D ADVERT_NAME='"UR500 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${BAYCKRC_UR500.lib_deps}
  ${sensor_base.lib_deps}
  ${esp32_ota.lib_deps}
  bakercp/CRC32 @ ^2.0.0

[env:BAYCKRC_UR500_room_server]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/simple_room_server/*.cpp>
build_flags =
  ${BAYCKRC_UR500.build_flags}
  ${sensor_base.build_flags}
  -UENV_INCLUDE_GPS
  -UENV_INCLUDE_VL53L0X
  -D ADVERT_NAME='"UR500 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
lib_deps =
  ${BAYCKRC_UR500.lib_deps}
  ${sensor_base.lib_deps}
  ${esp32_ota.lib_deps}
  bakercp/CRC32 @ ^2.0.0

[env:BAYCKRC_UR500_companion_radio_ble]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${BAYCKRC_UR500.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${BAYCKRC_UR500.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:BAYCKRC_UR500_companion_radio_usb]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${BAYCKRC_UR500.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D ENABLE_USB_INTERFACE
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${BAYCKRC_UR500.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:BAYCKRC_UR500_companion_radio_wifi]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/esp32/*.cpp>
build_flags =
  ${BAYCKRC_UR500.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
  -D WIFI_DEBUG_LOGGING=1
  -D WIFI_SSID='"myssid"'
  -D WIFI_PWD='"mypwd"'
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
lib_deps =
  ${BAYCKRC_UR500.lib_deps}
  ${esp32_ota.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:BAYCKRC_UR500_kiss_modem]
extends = BAYCKRC_UR500
build_src_filter = ${BAYCKRC_UR500.build_src_filter}
  +<../examples/kiss_modem/>
